### ISSUE TITLE
looking forward to your outstanding work!!!

### ISSUE THREAD

**Issue by nicebro123** [HuiZhang0812/DiffusionAD-Norm-guided-One-step-Denoising-Diffusion-for-Anomaly-Detection#1]

**Comment by KIM7AZEN** [comment]
+1

**Comment by abnilas** [comment]
+1

**Comment by xiaokai580** [comment]
Hello, do you reconstruct with one step approach? The one-step approximation I achieved was poor.

**Comment by Ace-blue** [comment]
cant wait to try

**Comment by jamdodot** [comment]
Do you know which journal the author selects for? How long until the publication

**Comment by jamdodot** [comment]
The author selects for CVPR, and the meeting will be held on June 20th, hoping to see the publication soon
